CREATE TABLE `pokemon` (
  `id_pokemon` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `nom` TEXT NOT NULL,
  `pv_max` INTEGER NOT NULL,
  `attaque` INTEGER NOT NULL,
  `defense` INTEGER NOT NULL,
  `vitesse` INTEGER NOT NULL,
  `image` TEXT NOT NULL,
  `id_type` INTEGER NOT NULL
);


CREATE TABLE `type` (
  `id_type` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `nom_type` TEXT NOT NULL
);






CREATE TABLE `potion` (
  `id_potion` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `nom` TEXT NOT NULL,
  `soin` INTEGER NOT NULL
);